### ISSUE TITLE
Problem when loading EA description

### ISSUE THREAD

**Issue by Ari-Wuria** [TomShen1234/EA-Center#2]
When updating for the EA description there seems like to have a problemw with the Zip framework added. (Don't know why this only happens to this EA in particular.)
Build in XCode shows a -999 Error, not really sure if this relates to the problem. 

<img width="1269" alt="2018-09-25 20 35 26" src="https://user-images.githubusercontent.com/43138121/46014670-a6f57680-c102-11e8-87bf-6107a9b87486.png">
<img width="430" alt="2018-09-25 20 35 34" src="https://user-images.githubusercontent.com/43138121/46014673-a9f06700-c102-11e8-969e-1a1007e81a62.png">

**Comment by TomShen1234** [comment]
There was a small glitch that happened in the server and it was fixed.
